# EC 1: NumPy Exercises
**Due: February 8, 9:30 AM**

In this extra credit assignment, you will practice doing linear algebra using the [NumPy Python package](https://numpy.org/). You are strongly encouraged to do this extra credit assignment if:
* you have never used NumPy before or you have not used it in a long time
* you have not taken DS-GA 1011 (Natural Language Processing with Representation Learning) and you are unsure of whether you have the necessary background for this course
* you want some easy extra credit points.

## Important: Read Before Starting

In the following exercises, you will need to implement functions defined in the `numpy_exercises` module. Please write all your code in the `numpy_exercises.py` file. You should not submit this notebook with your solutions, and we will not grade it if you do. Please be aware that code written in a Jupyter notebook may run differently when copied into Python modules.

This notebook comes with outputs for some, but not all, of the code cells. Thes outputs are the outputs that you should get **when all coding problems have been completed correctly**. You may obtain different results if you attempt to run the code cells before you have completed the coding problems, or if you have completed one or more coding problems incorrectly.

## Problem 1: Setup (0 Points in Total)

### Problem 1a: Install NumPy (No Submission, 0 Points)

For this course, you are strongly encouraged to download and install [Anaconda](https://www.anaconda.com), a free Python distribution that includes the `conda` package manager and comes with most of the packages you need (including NumPy) pre-installed. If you do not have Anaconda installed already, you should choose the latest version of the Individual Edition. Anaconda comes with a number of Python packages that are essential to working with neural networks, as well as the conda package manager.

If you don't have enough disk space for Anaconda, you can choose to install [Miniconda](https://docs.conda.io/en/latest/miniconda.html) instead. Miniconda a version of Anaconda includes Python as well as the `pip` and `conda` package managers, but does not come with NumPy or other tools pre-installed. 

If you choose to use Miniconda or an existing Python installation,<a name="cite_ref-1"></a>[<sup>[1]</sup>](#cite_note-1) please ensure you have the following installed.
* Python 3.5 or a later version
* The `pip` package manager or `conda` package manager. If you don’t have either package manager, please install pip by following the [official instructions](https://pip.pypa.io/en/stable/installation/).

The typical way to install NumPy is to simply run `pip install numpy` or `conda install numpy`. Please refer to the [NumPy installation instructions](https://numpy.org/install/) for detailed instructions specific to your machine. You can also install NumPy directly from this notebook by running one of the following two code cells; this is recommended if you are running this notebook on Google Colaboratory or some other web-based Jupyter notebook server.

In [ ]:
# Install NumPy using pip (recommended if you're on Google Colaboratory)
!pip install numpy

In [ ]:
# Install NumPy using conda
!conda install numpy

### Problem 1b: Import NumPy (No Submission, 0 Points)

Once you have installed NumPy, please import the NumPy package as follows. If the code cell below throws an error, then NumPy has not been installed correctly and you need to repeat Problem 1a.

In [1]:
import numpy as np

By convention, we typically refer to the NumPy package using the alias `np`.

## Problem 2: Basic Operations (9 Points in Total)

In the following exercises, you will read snippets of code and describe what they do in plain English. You are free to consult the [NumPy documentation](https://numpy.org/doc/stable/) as you complete these problems. You are also encouraged to run the code snippets in the Python console, in a Python script, or directly in the code cells below.<a name="cite_ref-2"></a>[<sup>[2]</sup>](#cite_note-2) Each code snippet assumes that all previous code snippets have already been run. Therefore, you must run the code snippets in the same order as they appear in the instructions.

### Problem 2a: The NumPy Array (Written, 1 Point)

The heart of NumPy is the _array_, a data type that represents vectors and matrices. Please create some arrays using the following code.

In [13]:
a = np.array(1)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

What mathematical objects are represented by `a`, `b`, `c`, and `d`?

**Ans:** 

a is an integer

b is a vector

c is a matrix
 
d is a tensor. 

### Problem 2b: Array Shapes (Written, 1 Point)

An important property of an array is its shape. Please run the following code
in order to inspect the shape of our arrays.



In [3]:
print(a.shape) 
print(b.shape) 
print(c.shape) 
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


What is the `.shape` of an array?

**Ans:** obtains the dimensions of a python object. 

### Problem 2c: Indexing (Written, 1 Point)

What do the following lines of code do? In your answer, refer to the lines by
their line number (line 1, line 2, etc.).

**Ans:**

line 1: 1st object of c in the first dimension.

line 2: 1st object of c in the second dimension. 

line 3: the last object of c in the first dimensioin. 

line 4: all of the objects of c starting from the 2nd object. 

line 5: adds another dimension to the array 


In [4]:
c[0]
c[:, 0]
c[-1]
c[1:]
c[:, np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

### Problem 2d: Arithmetic Operations (Written, 1 Point)

Please run the following lines of code.

In [8]:
print(c + c)
print(c - c) 
print(c * c) 
print(c / c)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


What do `+`, `-`, `*`, and `/` do?

`+`: element wise additiion
`-`: element wise subtraction 
`*`: element wise multiplication
`/`: element wise division

### Problem 2e: Matrix Operations (Written, 1 Point)

Please run the following code.

In [9]:
print(c.T)
print(c @ c.T)

[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


What does `.T` do? What does `@` do?

### Problem 2f: Batch Matrix Multiplication (Written, 1 Point)

Please run the following code.

`.T`: matrix transpose 

`@` matrix multiplication

In [15]:
# Create a random array of shape (2, 3, 4)
e = np.random.randint(-10, high=10, size=(2, 3, 4)) 

print(d @ e)
print((d @ e).shape)

[[[ -26   -9  -17   31]
  [ -74  -27  -62   67]]

 [[ -18   94 -112  -15]
  [ -27  127 -157  -18]]]
(2, 2, 4)


In [18]:
d.shape,e.shape

((2, 2, 3), (2, 3, 4))

In [33]:
shapes1 = (4,2,2,2,2,3)
shapes2 = (2,2,2,3,4)
(np.arange(np.prod(shapes1)).reshape(shapes1) @ np.arange(np.prod(shapes2)).reshape(shapes2)).shape

(4, 2, 2, 2, 2, 4)

What does `@` do when its arguments are 3-dimensional or higher-dimensional arrays?

matrix wisee element multiplication occurs when there are 3 dimensions

**Ans:** 

### Problem 2g: Axis-Wise Operations (Written, 1 Point)

Please run the following code.

In [11]:
print(c.sum()) 
print(c.sum(axis=0))
print(c.sum(axis=1)) 
print(c.sum(axis=1, keepdims=True))

21
[5 7 9]
[ 6 15]
[[ 6]
 [15]]


What does `.sum()` do? What do the `axis` and `keepdims` keyword parameters do?

`.sum()`: compute the sum of all elements in the array

`axis`: determines the dimension which the elements are summed over 

`keepdims`: maintaiins the dimension of the original array so it can broadcast correctly. 


### Problem 2h: Reshaping (Written, 1 Point)

Please run the following code.

In [12]:
f = d.reshape(6, 2)
print(d.shape)
print(d)
print(f.shape)
print(f)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


What does `.reshape` do? (You don't have to be very specific.)

**Ans:** reorders the elements of the array so the new array has the specified shape

### Problem 2i: Copying (Written, 1 Point)

Please run the following code.

In [13]:
# Without copying
f[2] = -1
print(f)
print(d)

# With copying
g = f.copy()
g[2] = -2
print(g)
print(d)

[[ 1  2]
 [ 3  4]
 [-1 -1]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2  3]
  [ 4 -1 -1]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2]
 [ 3  4]
 [-2 -2]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2  3]
  [ 4 -1 -1]]

 [[ 7  8  9]
  [10 11 12]]]


What is the difference between lines 2–4 and 7–10? What does this tell us about `.reshape`? How does `.copy` change things?

f is a variable that points to the same object as d. So when we modify f, we also modify d. 
However, `copy` generates a new array where each element is the same as the original. So modifying g doesn't change d. 

## Problem 3: Complex Operations (10 Points in Total)

Next, you will implement some array operations that are frequently used in machine learning. In each of the problems below, **you must implement the operation described using only one line of code**. Your one line of code cannot exceed 76 characters in width, excluding indentations. For each problem, you must fill out one of the functions in the numpy exercise.py file by replacing pass with your own code. Please read the [docstring](https://peps.python.org/pep-0257/) of each function for guidance on what each function should do. You should consult the NumPy documentation and look for operations that will help you implement the functions.

All functions you must implement for this problem are defined in the `numpy_exercises.py` file. To test them, please import these functions now by running the following code cell.

In [3]:
from numpy_exercises import sigmoid, zero_center, even_rows, mask, accuracy

To receive full credit, your code must behave as illustrated in the usage example for each problem.

### Problem 3a: Sigmoid Function (Code, 2 Points)

The _sigmoid_ function $\sigma:\mathbb{R} \to \mathbb{R}$ is given by
$$\sigma(x) = \frac{1}{1 + e^{-x}}$$
where $e = 2.718281828\dots$.

Please implement the `sigmoid` function, which applies $\sigma$ to each item in an array.

In [4]:
# Usage example
x = np.array([[-1, -.5, 0], 
              [1, .5, 0]])
sigmoid(x)

array([[0.26894142, 0.37754067, 0.5       ],
       [0.73105858, 0.62245933, 0.5       ]])

### Problem 3b: Zero-Centering (Code, 2 Points)

Please implement the `zero_center` function, which takes a matrix (i.e., a 2D array) and subtracts the mean value from each row.

In [5]:
# Usage example
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [-1, 3, 4]])
zero_center(x)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-3.,  1.,  2.]])

### Problem 3c: Select Even Rows (Code, 2 Points)

Please implement the `even_rows` function, which will pick out the rows of an array with even index.

In [6]:
# Usage example
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
even_rows(x)

array([[1, 2, 3],
       [7, 8, 9]])

### Problem 3d: Masking (Code, 2 Points)

Please implement the `mask` function, which will "mask out" a value from an array, replacing it with another value. Your code must apply to an array in-place; i.e., it must modify the entries of the original array rather than returning a new array.

In [7]:
# Usage example
x = np.array([[1, 2, 3], 
              [2, 1, 3], 
              [3, 2, 1]])
mask(x, 2, replace_with=0)  # Replace all 2s with 0
x

array([[1, 0, 3],
       [0, 1, 3],
       [3, 0, 1]])

### Problem 3e: Compute Accuracy (Code, 2 Points)

A _multi-class classifier_ is a function that takes an input and _classifies_ it into three or more possible _labels_. Typically, the output of a multi-class classifier is a matrix of _logit scores_, where each row corresponds to an input, each column corresponds corresponds to a label, and each logit score measures how "confidently" the model thinks each input belongs to each label.

For instance, suppose a multi-class classifier returns the following logit scores.
$$ \begin{bmatrix} 1.5 & -.75 & .25 \\ -2.1 & -1.3 & -.5 \\ -.1 & 2.5 & 1.4 \\ .3 & -.01 & .15 \end{bmatrix} $$
For input 0 (the first row), the multi-class classifier assigns a confidence of $1.5$ to the label 0 (the first column), $-.75$ to the label 1, and $.25$ to the label 2. Since label 0 has the highest logit score in the row, the multi-class classifier's _predicted label_ for row 0 is label 0. Similarly, the predicted labels for inputs 1, 2, and 3 are 2, 1, and 0, respectively.

Often times, we would like to measure how _accurate_ a multi-class classifier is. We do so by comparing the predicted labels for a set of inputs to a set of _gold labels_ provided by a human expert. The accuracy of the multi-class classifier is simply the proportion of examples for which the predicted labels match the gold labels. For instance, if a multi-class classifier predicts the labels 0, 2, 1, and 0 for four inputs whose gold labels are 0, 2, 1, and 2, respectively, then the accuracy of the classifier is .75.

Please implement the `accuracy` function, which computes accuracy given a matrix of logit scores produced by a multi-class classifier and a vector of gold labels.

In [8]:
# Usage example
logits = np.array([[1.5, -.75, .25],
                   [-2.1, -1.3, -.5],
                   [-.1, 2.5, 1.4],
                   [.3, -.01, .15]])
gold_labels = np.array([0, 2, 1, 2])
accuracy(logits, gold_labels)

0.75

## Problem 4: Analysis of Matrix Multiplication (6 Points in Total)

Python is a high-level programming language that is easy to learn and easy to read. The beauty and simplicity of Python comes at a cost, however: Python operations are notoriously slow compared to lower-level languages such as C. Fortunately, NumPy array operations implement many of the most common yet expensive linear algebra computations using optimized, pre-compiled C code. This means that the more you use NumPy operations, the more efficiently your Python code will run.

In this exercise, you will compare the performance of NumPy’s matrix multiplication operator against a pure Python implementation of matrix multiplication. Please import the functions for this problem now.

In [9]:
from numpy_exercises import matmul_pure_python, measure_time

### Problem 4a: Matrix Multiplication in Pure Python (Code, 3 Points)

Please implement the `matmul_pure_python` function, which applies matrix multiplication to its two arguments. Assume that matrices are represented as lists of lists of numbers: each list of numbers is a row, and the full matrix is a list of rows. You may assume that your inputs are always valid matrices. **Do not use NumPy for this function!** 

As in Problem 3, the behavior of your code must match the following usage example.

In [10]:
# Usage example
a = [[-10, 8, 5],
     [-6, -10, 3]]
b = [[-1, 8, 7, -2],
     [-4, 7, 3, 7],
     [5, -1, -7, -4]]
matmul_pure_python(a, b)

[[3, -29, -81, 56], [61, -121, -93, -70]]

### Problem 4b: Comparison of Pure Python with NumPy (Written, 3 Points)

Please run the function `measure_time` **after you have completed Problem 4a**. This function will generate two random matrices, multiply them using your pure Python implementation of matrix multiplication and using NumPy’s implementation of matrix multiplication, and report the running time of each implementation. 

In your submission, please answer the following questions.
* What were the running times reported by `measure_time` function?
* Which implementation was faster?
* Please include any thoughts or comments you have about your results.

**Ans:**

Numpy's implementation is faster. This is because Numpy is mostly written in C or C++, and uses vectorized programming, which makes it faster than base python. 

In [11]:
# Please run this cell after you have completed Problem 4a.
measure_time()

Matrix multiplication in pure Python took 4.387 seconds.
Matrix multiplication in NumPy took 0.016 seconds.


## Footnotes 

<a name="cite_note-1"></a>1. [<sup>^</sup>](#cite_ref-1) This is not recommended unless you have an existing Python or Anaconda setup that you are already accustomed to using. If you are new to Python, you should install Anaconda, even if your computer (Mac OS, Linux, and other Unix-based operating systems) has a pre-installed version of Python.

<a name="cite_note-2"></a>2. [<sup>^</sup>](#cite_ref-1) You may find it helpful to run each code snippet one line at a time in the Python console.